const char* msg[]=   
{
 "Error reading drive %u sector %u - %u!(0)\n"  /* 0 */
 ,"Error reading drive %u sector %u - %u!(1)\n" /* 1 */
 ,"Error writing drive %u sector %u - %u!(2)\n" /* 2 */
 ,"Error writing drive %u sector %u - %u!(3)\n" /* 3 */
 ,"Not enough memory. Could not setup cache. (4)\n" /* 4 */
 ,"Could not obtain lock level 0 for drive %c!(5)\nDo not use LFN Tools under Windows!\n" /* 5 */
 ,"Could not unlock drive %u!(6)\n" /* 6 */
 ,"Error getting disk information: %u!(7)\n" /* 7 */
 ,"Device busy!(8)\n" /* 8 */
 ,"Error getting track information: %s!(9)\n" /* 9 */
 ,"Forced Track (%u) out of range!(10)\n" /* 10 */
 ,"Forced Track (%u) is not a DATA track!(11)\n" /* 11 */
 ,"No data track found on drive %c!(12)\n" /* 12 */
 ,"Could not read from CD-ROM.(13)\n" /* 13 */
 ,"Cache failure!(14)\n" /* 14 */
 ,"Error reading CD-ROM (15)\n" /* 15 */
 ,"Could not read BPB!(16)\n" /* 16 */
 ,"Unknown file system!(17)\n" /* 17 */
 ,"Out of memory!(18)\n" /* 18*/
 ,"Out of memory! FAT corrupted on drive %c cluster %u! (19)\n" /* 19 */
 ,"Out of memory!(20)\n" /* 20 */
 ,"Unknown FAT type not supported!(21)\n" /* 21 */
 ,"Out of memory!(22)\n" /* 22 */
 ,"Unknown FAT type not supported!(23)\n" /* 23 */
 ,"Out of memory!(24)\n" /* 24 */
 ,"Out of memory!(25)\n" /* 25 */
 ,"Could not read directory!(26)\n" /* 26 */
 ,"Out of memory!(27)\n" /* 27 */
 ,"Unknown FAT type not supported!(28)\n" /* 28 */
 ,"Out of memory!(29)\n" /* 29 */
 ,"Out of memory!(30)\n" /* 30 */
 ,"Root is corrupt! Run ScanDisk!(31)\n" /* 31 */
 ,"FAT may be corrupt!(32)\n" /* 32 */
 ,"Directory is corrupt! Run ScanDisk!(33)\n" /* 33 */
 ,"Directory is corrupt! Run ScanDisk!(34)\n" /* 34 */
 ,"Directory is corrupt. Run ScanDisk!(35)\n" /* 35 */
 ,"Out of memory!(36)\n" /* 36 */
 ,"Corrupt FAT! Use Scandisk!(37)\n" /* 37 */
 ,"Unknown FAT type not supported!(38)\n" /* 38 */
 ,"Out of memory!(39)\n" /* 39 */
 ,"Could not read directory!(40)\n" /* 40 */
 ,"Out of memory!(41)\n" /* 41 */
 ,"Directory corrupt:duplicate filenames, first one deleted!(42)\n" /* 42 */
 ,"No space left in root directory! Can only hold %u entries.(43)\n" /* 43 */
 ,"Out of memory!(44)\n" /* 44 */
 ,"Disk Full!(45)\n" /* 45 */ 
 ,"Cannot handle CD-ROM format! (46)\n" /* 46 */
 ,"Out of Memory!(47)\n" /* 47 */
 ,"Out of Memory!(48)\n" /* 48 */  
 ,"Joliet and ISO9660 file systems differ!(49)\n" /* 49 */  
 ,"Ambiguous DPB!(50)\n" /* 50 */              
 ,"Sorry, drive does not support direct I/O!(51)\n" /* 51 */            
 ,"Not enough virtual memory (EMS,XMS) (52)\n" /* 52 */    
 ,"Virtual memory failure (53)\n" /* 53 */      
 ,"Too many cache pages! (54)\n" /* 54 */              
};