const char* msg[]=   
{
  "Lesefehler Laufwerk %u Sektoren %u - %u!(0)\n"  /* 0 */
 ,"Lesefehler Laufwerk %u Sektoren %u - %u!(1)\n" /* 1 */
 ,"Schreibfehler Laufwerk %u Sektoren %u - %u!(2)\n" /* 2 */
 ,"Schreibfehler Laufwerk %u Sektoren %u - %u!(3)\n" /* 3 */
 ,"Nicht genÅgend Speicher fÅr Cache. (4)\n" /* 4 */
 ,"Konnte Laufwerk %c nicht sperren (Level 0)!(5)\nLFN Tools laufen nicht unter Windows!\n" /* 5 */
 ,"Konnte Laufwerkssperre nicht aufheben auf Laufwerk %u!(6)\n" /* 6 */
 ,"Fehler beim Lesen der Laufwerksinfos: %u!(7)\n" /* 7 */
 ,"GerÑt wird gerade verwendet!(8)\n" /* 8 */
 ,"Fehler beim Lesen der Track-Infos: %s!(9)\n" /* 9 */
 ,"GewÅnschter Track (%u) ist ausserhalb des Bereichs!(10)\n" /* 10 */
 ,"GewÅnschter Track (%u) ist kein DATA Track!(11)\n" /* 11 */
 ,"Kein Datentrack auf Laufwerk %c gefunden!(12)\n" /* 12 */
 ,"Kann nicht vom CD-ROM lesen.(13)\n" /* 13 */
 ,"Cache Fehler! Bitte Hersteller kontaktieren.(14)\n" /* 14 */
 ,"Fehler beim Lesen von CD-ROM (15)\n" /* 15 */
 ,"Konnte BPB nicht lesen!(16)\n" /* 16 */
 ,"Unbekanntes Dateisystem!(17)\n" /* 17 */
 ,"Zuwenig Speicher!(18)\n" /* 18*/
 ,"Zuwenig Speicher! FAT beschÑdigt auf Laufwerk %c Cluster %u! (19)\n" /* 19 */
 ,"Zuwenig Speicher!(20)\n" /* 20 */
 ,"Unbekannter FAT Typ wird nicht unterstÅtzt!(21)\n" /* 21 */
 ,"Zuwenig Speicher!(22)\n" /* 22 */
 ,"Unbekannter FAT Typ wird nicht unterstÅtzt!(23)\n" /* 23 */
 ,"Zuwenig Speicher!(24)\n" /* 24 */
 ,"Zuwenig Speicher!(25)\n" /* 25 */
 ,"Verzeichnis konnte nicht gelesen werden!(26)\n" /* 26 */
 ,"Zuwenig Speicher!(27)\n" /* 27 */
 ,"Unbekannter FAT Typ wird nicht unterstÅtzt!(28)\n" /* 28 */
 ,"Zuwenig Speicher!(29)\n" /* 29 */
 ,"Zuwenig Speicher!(30)\n" /* 30 */
 ,"Hauptverzeichnis ist beschÑdigt! ScanDisk aufrufen!(31)\n" /* 31 */
 ,"Die FAT ist wahrscheinlich beschÑdigt!(32)\n" /* 32 */
 ,"Verzeichnis beschÑdigt! ScanDisk aufrufen!(33)\n" /* 33 */
 ,"Verzeichnis beschÑdigt! ScanDisk aufrufen!(34)\n" /* 34 */
 ,"Verzeichnis beschÑdigt! ScanDisk aufrufen!(35)\n" /* 35 */
 ,"Zuwenig Speicher!(36)\n" /* 36 */
 ,"FAT beschÑdigt! ScanDisk aufrufen!(37)\n" /* 37 */
 ,"Unbekannter FAT Typ wird nicht unterstÅtzt!(38)\n" /* 38 */
 ,"Zuwenig Speicher!(39)\n" /* 39 */
 ,"Verzeichnis konnte nicht gelesen werden!(40)\n" /* 40 */
 ,"Zuwenig Speicher!(41)\n" /* 41 */
 ,"Verzeichnis besch‰digt: doppelter Dateiname, erster wurde gelîscht!(42)\n" /* 42 */
 ,"Kein Platz mehr im Hauptverzeichnis! Maximal %u EintrÑge mîglich.(43)\n" /* 43 */
 ,"Zuwenig Speicher!(44)\n" /* 44 */
 ,"Laufwerk voll!(45)\n" /* 45 */ 
 ,"Unbekanntes CD-ROM Format! (46)\n" /* 46 */
 ,"Zuwenig Speicher!(47)\n" /* 47 */
 ,"Zuwenig Speicher!(48)\n" /* 48 */  
 ,"Joliet und ISO9660 Dateisysteme sind verschieden!(49)\n" /* 49 */ 
 ,"DPB unglaubw¸rdig!(50)\n" /* 50 */  
 ,"Das Laufwerk erlaubt kein direktes I/O!(51)\n" /* 51 */  
 ,"Zuwenig virtueller Speicher (EMS,XMS) (52)\n" /* 52 */      
 ,"Virtueller Speicher Fehler (53)\n" /* 53 */    
 ,"Zuviele Cacheseiten (54)\n" /* 54 */             
};